name: Deploy .NET app to Elastic Beanstalk

on:
  push:
    branches:
      - fatima

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish project
        run: dotnet publish -c Release -o publish

      - name: Zip publish folder
        run: zip -r deploy.zip publish/

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: CICD_uppgiften
          environment_name: CICDuppgiften-env
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
